### ISSUE TITLE
Todo 어플리케이션 요구사항 명세서

### ISSUE THREAD

**Issue by hojju** [hojju/Solo_Todo_App#1]
필요 기능
- Todo List 생성/조회/변경/삭제

할 일
1. [x] todo 테이블 만들기
2. [x] 생성 api 만들기
3. [x] 조회 api 만들기
4. [x] 변경 api 만들기
5. [x] 삭제 api 만들기
6. [x] 테스트

예상 시간: 10h
